name: web_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.3.8
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  logger: ^2.2.0
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  shared_preferences: ^2.2.3
  go_router: ^14.2.6
  url_strategy: ^0.3.0
  excel: ^4.0.3
  intl: ^0.19.0
  syncfusion_flutter_charts: ^ 25.2.4
  fl_chart: ^0.68.0
  marquee_list: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  flutter_gen_runner: any
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
